
package publicadores;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServicesControladorUsuario", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServicesControladorUsuario {


    /**
     * 
     * @return
     *     returns publicadores.WrapperSetString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/WebServicesControladorUsuario/mostrarNicknameSociosRequest", output = "http://publicadores/WebServicesControladorUsuario/mostrarNicknameSociosResponse")
    public WrapperSetString mostrarNicknameSocios();

    /**
     * 
     * @param arg0
     * @throws UsuarioDisponibilidadException_Exception
     */
    @WebMethod
    @Action(input = "http://publicadores/WebServicesControladorUsuario/altaUsuarioRequest", output = "http://publicadores/WebServicesControladorUsuario/altaUsuarioResponse", fault = {
        @FaultAction(className = UsuarioDisponibilidadException_Exception.class, value = "http://publicadores/WebServicesControladorUsuario/altaUsuario/Fault/UsuarioDisponibilidadException")
    })
    public void altaUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        InfoBasicaUser arg0)
        throws UsuarioDisponibilidadException_Exception
    ;

    /**
     * 
     * @return
     *     returns publicadores.WrapperListString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/WebServicesControladorUsuario/usuariosEnSistemaNickNameRequest", output = "http://publicadores/WebServicesControladorUsuario/usuariosEnSistemaNickNameResponse")
    public WrapperListString usuariosEnSistemaNickName();

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.WrapperSetString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/WebServicesControladorUsuario/mostrarNombreProfesoresDeInstitucionRequest", output = "http://publicadores/WebServicesControladorUsuario/mostrarNombreProfesoresDeInstitucionResponse")
    public WrapperSetString mostrarNombreProfesoresDeInstitucion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns publicadores.WrapperListString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/WebServicesControladorUsuario/institucionesEnSistemaRequest", output = "http://publicadores/WebServicesControladorUsuario/institucionesEnSistemaResponse")
    public WrapperListString institucionesEnSistema();

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.InformacionActividad
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/WebServicesControladorUsuario/informacionActividadRequest", output = "http://publicadores/WebServicesControladorUsuario/informacionActividadResponse")
    public InformacionActividad informacionActividad(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/WebServicesControladorUsuario/actualizarInformacionUsuarioRequest", output = "http://publicadores/WebServicesControladorUsuario/actualizarInformacionUsuarioResponse")
    public void actualizarInformacionUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        InfoBasicaUser arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.InfoBasicaUser
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/WebServicesControladorUsuario/informacionBasicaUsuarioRequest", output = "http://publicadores/WebServicesControladorUsuario/informacionBasicaUsuarioResponse")
    public InfoBasicaUser informacionBasicaUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns publicadores.WrapperSetString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/WebServicesControladorUsuario/mostrarCuponerasDisponiblesRequest", output = "http://publicadores/WebServicesControladorUsuario/mostrarCuponerasDisponiblesResponse")
    public WrapperSetString mostrarCuponerasDisponibles(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/WebServicesControladorUsuario/seguirUsuarioRequest", output = "http://publicadores/WebServicesControladorUsuario/seguirUsuarioResponse")
    public void seguirUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/WebServicesControladorUsuario/dejarDeSeguirUsuarioRequest", output = "http://publicadores/WebServicesControladorUsuario/dejarDeSeguirUsuarioResponse")
    public void dejarDeSeguirUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws UsuarioInexistenteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/WebServicesControladorUsuario/esSocioRequest", output = "http://publicadores/WebServicesControladorUsuario/esSocioResponse", fault = {
        @FaultAction(className = UsuarioInexistenteException_Exception.class, value = "http://publicadores/WebServicesControladorUsuario/esSocio/Fault/UsuarioInexistenteException")
    })
    public boolean esSocio(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioInexistenteException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns publicadores.WrapperStringNull
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/WebServicesControladorUsuario/autenticarUsarioRequest", output = "http://publicadores/WebServicesControladorUsuario/autenticarUsarioResponse")
    public WrapperStringNull autenticarUsario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns publicadores.WrapperStringNull
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/WebServicesControladorUsuario/autenticarUsarioMovilRequest", output = "http://publicadores/WebServicesControladorUsuario/autenticarUsarioMovilResponse")
    public WrapperStringNull autenticarUsarioMovil(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/WebServicesControladorUsuario/getNicknameUsuarioRequest", output = "http://publicadores/WebServicesControladorUsuario/getNicknameUsuarioResponse")
    public String getNicknameUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.WrapperListString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/WebServicesControladorUsuario/usuariosSiguiendoRequest", output = "http://publicadores/WebServicesControladorUsuario/usuariosSiguiendoResponse")
    public WrapperListString usuariosSiguiendo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.WrapperListString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/WebServicesControladorUsuario/usuariosSeguidoresRequest", output = "http://publicadores/WebServicesControladorUsuario/usuariosSeguidoresResponse")
    public WrapperListString usuariosSeguidores(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.WrapperDataCuponera
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/WebServicesControladorUsuario/cuponerasRequest", output = "http://publicadores/WebServicesControladorUsuario/cuponerasResponse")
    public WrapperDataCuponera cuponeras(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.InfoActividadProfe
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/WebServicesControladorUsuario/informacionActDepEstadoIngRechRequest", output = "http://publicadores/WebServicesControladorUsuario/informacionActDepEstadoIngRechResponse")
    public InfoActividadProfe informacionActDepEstadoIngRech(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/WebServicesControladorUsuario/usuarioSigueAUsuarioRequest", output = "http://publicadores/WebServicesControladorUsuario/usuarioSigueAUsuarioResponse")
    public boolean usuarioSigueAUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.WrapperListString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/WebServicesControladorUsuario/getGanadoresDeClaseRequest", output = "http://publicadores/WebServicesControladorUsuario/getGanadoresDeClaseResponse")
    public WrapperListString getGanadoresDeClase(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.WrapperListDtPremio
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/WebServicesControladorUsuario/getPremiosDeUsuarioRequest", output = "http://publicadores/WebServicesControladorUsuario/getPremiosDeUsuarioResponse")
    public WrapperListDtPremio getPremiosDeUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns publicadores.InfoBasicaSocio
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/WebServicesControladorUsuario/sinProposito1Request", output = "http://publicadores/WebServicesControladorUsuario/sinProposito1Response")
    public InfoBasicaSocio sinProposito1();

    /**
     * 
     * @return
     *     returns publicadores.InfoBasicaProfesor
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/WebServicesControladorUsuario/sinProposito2Request", output = "http://publicadores/WebServicesControladorUsuario/sinProposito2Response")
    public InfoBasicaProfesor sinProposito2();

    /**
     * 
     * @return
     *     returns publicadores.InfoActividadProfe
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/WebServicesControladorUsuario/sinProposito3Request", output = "http://publicadores/WebServicesControladorUsuario/sinProposito3Response")
    public InfoActividadProfe sinProposito3();

    /**
     * 
     * @return
     *     returns publicadores.InfoActividadSocio
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/WebServicesControladorUsuario/sinProposito4Request", output = "http://publicadores/WebServicesControladorUsuario/sinProposito4Response")
    public InfoActividadSocio sinProposito4();

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.InfoActividadProfe
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/WebServicesControladorUsuario/todasLasActividadesDeUnProfesorRequest", output = "http://publicadores/WebServicesControladorUsuario/todasLasActividadesDeUnProfesorResponse")
    public InfoActividadProfe todasLasActividadesDeUnProfesor(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.WrapperListaUsuarios
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/WebServicesControladorUsuario/darParticipantesRequest", output = "http://publicadores/WebServicesControladorUsuario/darParticipantesResponse")
    public WrapperListaUsuarios darParticipantes(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
