
package publicadores;

import java.io.FileReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServicesCuponerasService", targetNamespace = "http://Publicadores/", wsdlLocation = "http://localhost:9128/CtrlCuponeras?wsdl")
public class WebServicesCuponerasService
    extends Service
{

    private final static URL WEBSERVICESCUPONERASSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICESCUPONERASSERVICE_EXCEPTION;
    private final static QName WEBSERVICESCUPONERASSERVICE_QNAME = new QName("http://Publicadores/", "WebServicesCuponerasService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	Properties p = null;
        	String valUrl = "";
        	try {
    	    	FileReader reader=new FileReader("/entrenamosUy/conf.properties");  
    	    	p=new Properties();  
    	    	p.load(reader); 
    	    	valUrl = p.getProperty("urlCuponerasWeb");
        	} catch (Exception ex) {}
            url = new URL(valUrl);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICESCUPONERASSERVICE_WSDL_LOCATION = url;
        WEBSERVICESCUPONERASSERVICE_EXCEPTION = e;
    }

    public WebServicesCuponerasService() {
        super(__getWsdlLocation(), WEBSERVICESCUPONERASSERVICE_QNAME);
    }

    public WebServicesCuponerasService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICESCUPONERASSERVICE_QNAME, features);
    }

    public WebServicesCuponerasService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICESCUPONERASSERVICE_QNAME);
    }

    public WebServicesCuponerasService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICESCUPONERASSERVICE_QNAME, features);
    }

    public WebServicesCuponerasService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServicesCuponerasService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServicesCuponeras
     */
    @WebEndpoint(name = "WebServicesCuponerasPort")
    public WebServicesCuponeras getWebServicesCuponerasPort() {
        return super.getPort(new QName("http://Publicadores/", "WebServicesCuponerasPort"), WebServicesCuponeras.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServicesCuponeras
     */
    @WebEndpoint(name = "WebServicesCuponerasPort")
    public WebServicesCuponeras getWebServicesCuponerasPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Publicadores/", "WebServicesCuponerasPort"), WebServicesCuponeras.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICESCUPONERASSERVICE_EXCEPTION!= null) {
            throw WEBSERVICESCUPONERASSERVICE_EXCEPTION;
        }
        return WEBSERVICESCUPONERASSERVICE_WSDL_LOCATION;
    }

}
