
package publicadores;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "UsuarioDisponibilidadException", targetNamespace = "http://Publicadores/")
public class UsuarioDisponibilidadException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UsuarioDisponibilidadException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UsuarioDisponibilidadException_Exception(String message, UsuarioDisponibilidadException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public UsuarioDisponibilidadException_Exception(String message, UsuarioDisponibilidadException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicadores.UsuarioDisponibilidadException
     */
    public UsuarioDisponibilidadException getFaultInfo() {
        return faultInfo;
    }

}
