
package publicadores;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServicesControladorUsuario", targetNamespace = "http://Publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServicesControladorUsuario {


    /**
     * 
     * @return
     *     returns publicadores.WrapperListString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/WebServicesControladorUsuario/usuariosEnSistemaNickNameRequest", output = "http://Publicadores/WebServicesControladorUsuario/usuariosEnSistemaNickNameResponse")
    public WrapperListString usuariosEnSistemaNickName();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/WebServicesControladorUsuario/chauRequest", output = "http://Publicadores/WebServicesControladorUsuario/chauResponse")
    public String chau();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/WebServicesControladorUsuario/usuarioSigueAUsuarioRequest", output = "http://Publicadores/WebServicesControladorUsuario/usuarioSigueAUsuarioResponse")
    public boolean usuarioSigueAUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws UsuarioInexistenteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/WebServicesControladorUsuario/esSocioRequest", output = "http://Publicadores/WebServicesControladorUsuario/esSocioResponse", fault = {
        @FaultAction(className = UsuarioInexistenteException_Exception.class, value = "http://Publicadores/WebServicesControladorUsuario/esSocio/Fault/UsuarioInexistenteException")
    })
    public boolean esSocio(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioInexistenteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.WrapperListString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/WebServicesControladorUsuario/usuariosSiguiendoRequest", output = "http://Publicadores/WebServicesControladorUsuario/usuariosSiguiendoResponse")
    public WrapperListString usuariosSiguiendo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.WrapperListString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/WebServicesControladorUsuario/usuariosSeguidoresRequest", output = "http://Publicadores/WebServicesControladorUsuario/usuariosSeguidoresResponse")
    public WrapperListString usuariosSeguidores(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.InfoBasicaUser
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/WebServicesControladorUsuario/informacionBasicaUsuarioRequest", output = "http://Publicadores/WebServicesControladorUsuario/informacionBasicaUsuarioResponse")
    public InfoBasicaUser informacionBasicaUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns publicadores.InfoBasicaSocio
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/WebServicesControladorUsuario/sinProposito1Request", output = "http://Publicadores/WebServicesControladorUsuario/sinProposito1Response")
    public InfoBasicaSocio sinProposito1();

    /**
     * 
     * @return
     *     returns publicadores.InfoBasicaProfesor
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/WebServicesControladorUsuario/sinProposito2Request", output = "http://Publicadores/WebServicesControladorUsuario/sinProposito2Response")
    public InfoBasicaProfesor sinProposito2();

    /**
     * 
     * @return
     *     returns publicadores.InfoActividadProfe
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/WebServicesControladorUsuario/sinProposito3Request", output = "http://Publicadores/WebServicesControladorUsuario/sinProposito3Response")
    public InfoActividadProfe sinProposito3();

    /**
     * 
     * @return
     *     returns publicadores.InfoActividadSocio
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/WebServicesControladorUsuario/sinProposito4Request", output = "http://Publicadores/WebServicesControladorUsuario/sinProposito4Response")
    public InfoActividadSocio sinProposito4();

    /**
     * 
     * @return
     *     returns java.lang.Object
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/WebServicesControladorUsuario/sinProposito5Request", output = "http://Publicadores/WebServicesControladorUsuario/sinProposito5Response")
    public Object sinProposito5();

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.InformacionActividad
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/WebServicesControladorUsuario/informacionActividadRequest", output = "http://Publicadores/WebServicesControladorUsuario/informacionActividadResponse")
    public InformacionActividad informacionActividad(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.WrapperDataCuponera
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/WebServicesControladorUsuario/cuponerasRequest", output = "http://Publicadores/WebServicesControladorUsuario/cuponerasResponse")
    public WrapperDataCuponera cuponeras(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.InfoActividadProfe
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/WebServicesControladorUsuario/informacionActDepEstadoIngRechRequest", output = "http://Publicadores/WebServicesControladorUsuario/informacionActDepEstadoIngRechResponse")
    public InfoActividadProfe informacionActDepEstadoIngRech(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.Object
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/WebServicesControladorUsuario/aaaaaaaRequest", output = "http://Publicadores/WebServicesControladorUsuario/aaaaaaaResponse")
    public Object aaaaaaa();

}
