
package publicadores;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServicesCuponeras", targetNamespace = "http://Publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServicesCuponeras {


    /**
     * 
     */
    @WebMethod
    @Action(input = "http://Publicadores/WebServicesCuponeras/cargarDatosCuponerasRequest", output = "http://Publicadores/WebServicesCuponeras/cargarDatosCuponerasResponse")
    public void cargarDatosCuponeras();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws CuponeraCompradaException_Exception
     */
    @WebMethod
    @Action(input = "http://Publicadores/WebServicesCuponeras/comprarCuponeraRequest", output = "http://Publicadores/WebServicesCuponeras/comprarCuponeraResponse", fault = {
        @FaultAction(className = CuponeraCompradaException_Exception.class, value = "http://Publicadores/WebServicesCuponeras/comprarCuponera/Fault/CuponeraCompradaException")
    })
    public void comprarCuponera(
        @WebParam(name = "arg0", partName = "arg0")
        XMLGregorianCalendar arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2)
        throws CuponeraCompradaException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.WrapperSetString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/WebServicesCuponeras/getCuponerasCategoriaRequest", output = "http://Publicadores/WebServicesCuponeras/getCuponerasCategoriaResponse")
    public WrapperSetString getCuponerasCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.WrapperSetString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/WebServicesCuponeras/getCuponerasInstitucionRequest", output = "http://Publicadores/WebServicesCuponeras/getCuponerasInstitucionResponse")
    public WrapperSetString getCuponerasInstitucion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.WrapperSetString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/WebServicesCuponeras/getCuponerasADRequest", output = "http://Publicadores/WebServicesCuponeras/getCuponerasADResponse")
    public WrapperSetString getCuponerasAD(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.WrapperSetDataCuponera
     * @throws CuponeraNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/WebServicesCuponeras/buscarCuponerasRequest", output = "http://Publicadores/WebServicesCuponeras/buscarCuponerasResponse", fault = {
        @FaultAction(className = CuponeraNoExisteException_Exception.class, value = "http://Publicadores/WebServicesCuponeras/buscarCuponeras/Fault/CuponeraNoExisteException")
    })
    public WrapperSetDataCuponera buscarCuponeras(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws CuponeraNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.WrapperSetString
     * @throws CuponeraNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/WebServicesCuponeras/getCuponerasActividadRequest", output = "http://Publicadores/WebServicesCuponeras/getCuponerasActividadResponse", fault = {
        @FaultAction(className = CuponeraNoExisteException_Exception.class, value = "http://Publicadores/WebServicesCuponeras/getCuponerasActividad/Fault/CuponeraNoExisteException")
    })
    public WrapperSetString getCuponerasActividad(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws CuponeraNoExisteException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns publicadores.WrapperSetString
     * @throws ActividadDeportivaNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/WebServicesCuponeras/listarActividadesfaltantesRequest", output = "http://Publicadores/WebServicesCuponeras/listarActividadesfaltantesResponse", fault = {
        @FaultAction(className = ActividadDeportivaNoExisteException_Exception.class, value = "http://Publicadores/WebServicesCuponeras/listarActividadesfaltantes/Fault/ActividadDeportivaNoExisteException")
    })
    public WrapperSetString listarActividadesfaltantes(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws ActividadDeportivaNoExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns publicadores.WrapperSetString
     * @throws CuponeraNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/WebServicesCuponeras/listarcuponeraslibresRequest", output = "http://Publicadores/WebServicesCuponeras/listarcuponeraslibresResponse", fault = {
        @FaultAction(className = CuponeraNoExisteException_Exception.class, value = "http://Publicadores/WebServicesCuponeras/listarcuponeraslibres/Fault/CuponeraNoExisteException")
    })
    public WrapperSetString listarcuponeraslibres()
        throws CuponeraNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.DataCuponera
     * @throws CuponeraNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/WebServicesCuponeras/mostrarCuponeraRequest", output = "http://Publicadores/WebServicesCuponeras/mostrarCuponeraResponse", fault = {
        @FaultAction(className = CuponeraNoExisteException_Exception.class, value = "http://Publicadores/WebServicesCuponeras/mostrarCuponera/Fault/CuponeraNoExisteException")
    })
    public DataCuponera mostrarCuponera(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws CuponeraNoExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns publicadores.WrapperSetString
     * @throws CuponeraNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/WebServicesCuponeras/listarCuponerasRequest", output = "http://Publicadores/WebServicesCuponeras/listarCuponerasResponse", fault = {
        @FaultAction(className = CuponeraNoExisteException_Exception.class, value = "http://Publicadores/WebServicesCuponeras/listarCuponeras/Fault/CuponeraNoExisteException")
    })
    public WrapperSetString listarCuponeras()
        throws CuponeraNoExisteException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws ActividadDeportivaRepetidaException_Exception
     */
    @WebMethod
    @Action(input = "http://Publicadores/WebServicesCuponeras/agregarActividadRequest", output = "http://Publicadores/WebServicesCuponeras/agregarActividadResponse", fault = {
        @FaultAction(className = ActividadDeportivaRepetidaException_Exception.class, value = "http://Publicadores/WebServicesCuponeras/agregarActividad/Fault/ActividadDeportivaRepetidaException")
    })
    public void agregarActividad(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2)
        throws ActividadDeportivaRepetidaException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @throws CuponeraRepetidaException_Exception
     */
    @WebMethod
    @Action(input = "http://Publicadores/WebServicesCuponeras/registrarCuponeraRequest", output = "http://Publicadores/WebServicesCuponeras/registrarCuponeraResponse", fault = {
        @FaultAction(className = CuponeraRepetidaException_Exception.class, value = "http://Publicadores/WebServicesCuponeras/registrarCuponera/Fault/CuponeraRepetidaException")
    })
    public void registrarCuponera(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        XMLGregorianCalendar arg2,
        @WebParam(name = "arg3", partName = "arg3")
        XMLGregorianCalendar arg3,
        @WebParam(name = "arg4", partName = "arg4")
        float arg4,
        @WebParam(name = "arg5", partName = "arg5")
        XMLGregorianCalendar arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6)
        throws CuponeraRepetidaException_Exception
    ;

}
