
package src.publicadores;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import net.java.dev.jaxb.array.StringArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServicesIDeportivas", targetNamespace = "http://Publicadores.src/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    net.java.dev.jaxb.array.ObjectFactory.class,
    src.publicadores.ObjectFactory.class
})
public interface WebServicesIDeportivas {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws InstitucionDeportivaRepetidaException_Exception
     */
    @WebMethod
    @Action(input = "http://Publicadores.src/WebServicesIDeportivas/altaInstitucionRequest", output = "http://Publicadores.src/WebServicesIDeportivas/altaInstitucionResponse", fault = {
        @FaultAction(className = InstitucionDeportivaRepetidaException_Exception.class, value = "http://Publicadores.src/WebServicesIDeportivas/altaInstitucion/Fault/InstitucionDeportivaRepetidaException")
    })
    public void altaInstitucion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2)
        throws InstitucionDeportivaRepetidaException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns src.publicadores.DataInstitucion
     * @throws InstitucionDeportivaNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores.src/WebServicesIDeportivas/getInstitucionRequest", output = "http://Publicadores.src/WebServicesIDeportivas/getInstitucionResponse", fault = {
        @FaultAction(className = InstitucionDeportivaNoExisteException_Exception.class, value = "http://Publicadores.src/WebServicesIDeportivas/getInstitucion/Fault/InstitucionDeportivaNoExisteException")
    })
    public DataInstitucion getInstitucion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws InstitucionDeportivaNoExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns src.publicadores.DataInstitucionArray
     * @throws InstitucionDeportivaNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores.src/WebServicesIDeportivas/getInstitucionesRequest", output = "http://Publicadores.src/WebServicesIDeportivas/getInstitucionesResponse", fault = {
        @FaultAction(className = InstitucionDeportivaNoExisteException_Exception.class, value = "http://Publicadores.src/WebServicesIDeportivas/getInstituciones/Fault/InstitucionDeportivaNoExisteException")
    })
    public DataInstitucionArray getInstituciones()
        throws InstitucionDeportivaNoExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores.src/WebServicesIDeportivas/darNombreInstitucionesRequest", output = "http://Publicadores.src/WebServicesIDeportivas/darNombreInstitucionesResponse")
    public StringArray darNombreInstituciones();

    /**
     * 
     * @return
     *     returns src.publicadores.DataInstitucion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores.src/WebServicesIDeportivas/newDataInstitucionRequest", output = "http://Publicadores.src/WebServicesIDeportivas/newDataInstitucionResponse")
    public DataInstitucion newDataInstitucion();

}
