
package src.publicadores;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServicesCuponeras", targetNamespace = "http://Publicadores.src/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServicesCuponeras {


    /**
     * 
     * @param arg0
     * @return
     *     returns src.publicadores.WrapperSetString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores.src/WebServicesCuponeras/getCuponerasCategoriaRequest", output = "http://Publicadores.src/WebServicesCuponeras/getCuponerasCategoriaResponse")
    public WrapperSetString getCuponerasCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns src.publicadores.WrapperSetString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores.src/WebServicesCuponeras/getCuponerasInstitucionRequest", output = "http://Publicadores.src/WebServicesCuponeras/getCuponerasInstitucionResponse")
    public WrapperSetString getCuponerasInstitucion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns src.publicadores.WrapperSetString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores.src/WebServicesCuponeras/getCuponerasADRequest", output = "http://Publicadores.src/WebServicesCuponeras/getCuponerasADResponse")
    public WrapperSetString getCuponerasAD(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns src.publicadores.WrapperSetDataCuponera
     * @throws CuponeraNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores.src/WebServicesCuponeras/buscarCuponerasRequest", output = "http://Publicadores.src/WebServicesCuponeras/buscarCuponerasResponse", fault = {
        @FaultAction(className = CuponeraNoExisteException_Exception.class, value = "http://Publicadores.src/WebServicesCuponeras/buscarCuponeras/Fault/CuponeraNoExisteException")
    })
    public WrapperSetDataCuponera buscarCuponeras(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws CuponeraNoExisteException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws CuponeraCompradaException_Exception
     */
    @WebMethod
    @Action(input = "http://Publicadores.src/WebServicesCuponeras/comprarCuponeraRequest", output = "http://Publicadores.src/WebServicesCuponeras/comprarCuponeraResponse", fault = {
        @FaultAction(className = CuponeraCompradaException_Exception.class, value = "http://Publicadores.src/WebServicesCuponeras/comprarCuponera/Fault/CuponeraCompradaException")
    })
    public void comprarCuponera(
        @WebParam(name = "arg0", partName = "arg0")
        XMLGregorianCalendar arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2)
        throws CuponeraCompradaException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns src.publicadores.WrapperSetString
     * @throws CuponeraNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores.src/WebServicesCuponeras/getCuponerasActividadRequest", output = "http://Publicadores.src/WebServicesCuponeras/getCuponerasActividadResponse", fault = {
        @FaultAction(className = CuponeraNoExisteException_Exception.class, value = "http://Publicadores.src/WebServicesCuponeras/getCuponerasActividad/Fault/CuponeraNoExisteException")
    })
    public WrapperSetString getCuponerasActividad(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws CuponeraNoExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns src.publicadores.WrapperSetString
     * @throws CuponeraNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores.src/WebServicesCuponeras/listarcuponeraslibresRequest", output = "http://Publicadores.src/WebServicesCuponeras/listarcuponeraslibresResponse", fault = {
        @FaultAction(className = CuponeraNoExisteException_Exception.class, value = "http://Publicadores.src/WebServicesCuponeras/listarcuponeraslibres/Fault/CuponeraNoExisteException")
    })
    public WrapperSetString listarcuponeraslibres()
        throws CuponeraNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns src.publicadores.DataCuponera
     * @throws CuponeraNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores.src/WebServicesCuponeras/mostrarCuponeraRequest", output = "http://Publicadores.src/WebServicesCuponeras/mostrarCuponeraResponse", fault = {
        @FaultAction(className = CuponeraNoExisteException_Exception.class, value = "http://Publicadores.src/WebServicesCuponeras/mostrarCuponera/Fault/CuponeraNoExisteException")
    })
    public DataCuponera mostrarCuponera(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws CuponeraNoExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns src.publicadores.WrapperSetString
     * @throws CuponeraNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores.src/WebServicesCuponeras/listarCuponerasRequest", output = "http://Publicadores.src/WebServicesCuponeras/listarCuponerasResponse", fault = {
        @FaultAction(className = CuponeraNoExisteException_Exception.class, value = "http://Publicadores.src/WebServicesCuponeras/listarCuponeras/Fault/CuponeraNoExisteException")
    })
    public WrapperSetString listarCuponeras()
        throws CuponeraNoExisteException_Exception
    ;

    /**
     * 
     * @param fileName
     * @return
     *     returns byte[]
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores.src/WebServicesCuponeras/getFileRequest", output = "http://Publicadores.src/WebServicesCuponeras/getFileResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://Publicadores.src/WebServicesCuponeras/getFile/Fault/IOException")
    })
    public byte[] getFile(
        @WebParam(name = "fileName", partName = "fileName")
        String fileName)
        throws IOException_Exception
    ;

}
