
package publicadores;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InstitucionDeportivaNoExisteException", targetNamespace = "http://Publicadores/")
public class InstitucionDeportivaNoExisteException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InstitucionDeportivaNoExisteException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InstitucionDeportivaNoExisteException_Exception(String message, InstitucionDeportivaNoExisteException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InstitucionDeportivaNoExisteException_Exception(String message, InstitucionDeportivaNoExisteException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicadores.InstitucionDeportivaNoExisteException
     */
    public InstitucionDeportivaNoExisteException getFaultInfo() {
        return faultInfo;
    }

}
