
package publicadores;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ClaseNoExisteException", targetNamespace = "http://Publicadores/")
public class ClaseNoExisteException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ClaseNoExisteException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ClaseNoExisteException_Exception(String message, ClaseNoExisteException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ClaseNoExisteException_Exception(String message, ClaseNoExisteException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicadores.ClaseNoExisteException
     */
    public ClaseNoExisteException getFaultInfo() {
        return faultInfo;
    }

}
